# Generated by Django 5.1.5 on 2025-03-01 02:56

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profile_identification_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+5589999999999', max_length=128, region=None, verbose_name='Phone Number'),
        ),
    ]
