# Generated by Django 5.1.5 on 2025-03-01 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Date of Birth'),
        ),
    ]
